---
dist: bionic

services:
  - docker

before_install:
  - docker pull lihame/course-doc

script:
  - ./_compile_doc.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: out
  on:
    branch: master