title: JUG Events and Talks
description: JUG Talks Finder
root: /talkfinder/

exclude:
  - Gemfile
  - Gemfile.lock
  - talks_pre_en.adoc
  - talks_pre_ru.adoc
  - vendor/

keep_files:
  - images
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
    - imagesdir=/talkfinder/images

url: "https://jugspeakers.online/talkfinder" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap