---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true
          working-directory: jekyll
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up graphicsmagick
        run: sudo apt-get install -y graphicsmagick
      - name: install dependencies
        run: npm install
      - name: Build the site
        run: ./_compile_doc.sh 
        
      - name: Deploy to jugspeakers.online
        if: success() && github.ref == 'refs/heads/master'
        run: ./deploy.sh
        env:
          DECYPHER_KEY: ${{ secrets.DECYPHER_KEY }}
          GH_BUILD_NUMBER: ${{ github.run_number }}
